This is a code of a simple webapp which will be used to run the app in the browser.

from flask import Flask
app = Flask(__name__)

@app.route("/")
def main():
    return "Welcome!"

@app.route('/how are you')
def hello():
    return 'I am good, how about you?'

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)


    


    How to dockerize an application?
    yum update 
    yum install python
    yum install -y python pip
    Create/copy application code to /opt/app.py

    Run: FLASK_APP=app.py flask run --host=0.0.0.0

    > create a directory
    > create a file inside the directory eg, my-simple-webapp.
    > paste the source code of hte webapp inside the file.

    Now, we need to run the doocker build command.
    type: docker build .  , it will start to buil the image.

    What is a docker file?
    Docker file is a simple file with instructions to build an image.
    It is an automation of docker image creation.

    Important instructions:
    FROM
    RUN
    CMD
    
    Step
    
    How to build an image from docker file?